export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
